version: '3'

networks:
  app-network:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    networks:
      - app-network
    ports:
      - "3306:3306"
    container_name: cbi_mysql
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: webdeveloper
      MYSQL_PASSWORD: sdaqwerty!
      MYSQL_ROOT_PASSWORD: sdaqwerty!

  php:
    depends_on:
      - mysql
    networks:
      - app-network
    build:
      context: .
    container_name: cbi_php
    volumes:
      - ./php-conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./wordpress:/var/www/html
      - /var/www/html/wp-content/themes/cbi/node_modules
    restart: always
    expose:
      - "9001"

  nginx:
    depends_on:
      - php
    networks:
      - app-network
    image: nginx:latest
    container_name: cbi_nginx
    restart: always
    ports:
      - "9009:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
      - /var/www/html/wp-content/themes/cbi/node_modules

  phpmyadmin:
    depends_on:
      - mysql
    networks:
      - app-network
    image: phpmyadmin/phpmyadmin
    container_name: cbi_phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysql
    volumes:
      - ./php-conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
      
networks:
  app-network:
    driver: bridge
