version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: webdeveloper
      MYSQL_PASSWORD: sdaqwerty!
      MYSQL_ROOT_PASSWORD: sdaqwerty!

  php:
    depends_on:
      - mysql
    build:
      context: .
    container_name: php
    volumes:
      - ./php-conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./wordpress:/var/www/html
      - /var/www/html/wp-content/themes/cbi/node_modules
    links:
      - mysql
    restart: always
    expose:
      - 9001

  nginx:
    depends_on:
      - php
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 9009:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
      - /var/www/html/wp-content/themes/cbi/node_modules

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
    volumes:
      - ./php-conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
